Code_Fun_Do/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('User.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.conf.urls import url
from . import views
from models import Developer

app_name = 'User'


urlpatterns = [
	#/games/
	url(r'^$', views.IndexView.as_view(), name = 'index'),

	url(r'developer/add/$', views.DeveloperCreate.as_view(), name = 'developer-add'),

	#/games/developers
	url(r'^developers/$', views.DeveloperDetailsView.as_view(), name = 'developer-detail'),
	#/games/developer/2/
	url(r'developer/(?P<pk>[0-9]+)/$', views.DeveloperUpdate.as_view(), name = 'developer-update'),

	#games/developer/2/delete
	url(r'developer/(?P<pk>[0-9]+)/delete/$', views.DeveloperDelete.as_view(), name = 'developer-delete'),
	
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'),

	url(r'^devlogin(?P<pk>[0-9]+)/$', views.LoginDetailView.as_view(), name = 'login-detail'),
	

	url(r'^register/$', views.UserFormView.as_view(), name = 'register'),

	url(r'^login/$', views.LoginView.as_view(), name = 'login'),
	
	url(r'^logout/$', views.user_logout, name = 'logout'),

	url(r'^search/$', views.search, name = 'search')
	]

#CreateView.as_view(model=Developer, success_url=reverse('index'))

User/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django import forms


'''

class User(models.Model):

	user_name = models.CharField(max_length=100)
	user_profile_picture = models.FileField(max_length=1000)
	user_age = models.IntegerField(default=20)
	user_profession = models.CharField(max_length=50)
	user_tags = models.CharField(max_length = 100)

	def __unicode__(self):
		return self.user_name
'''

class Developer(models.Model):

   	user = models.OneToOneField(User, default=None)
   	developer_name = models.CharField(max_length=100, default='')
   	developer_logo = models.FileField()
   	developer_headquarters = models.CharField(max_length=100)
	developer_address = models.CharField(max_length=1000, default = '')
	developer_contact = models.CharField(max_length=100, default = '')
   	developer_tags = models.CharField(max_length=100, default='Separate by comma')

   	def __unicode__(self):
		return self.developer_name

	def get_absolute_url(self):
		return reverse('User:detail', kwargs={'pk':self.pk})

	def developer_tag_list(self):
		return self.developer_tags.split(',')

class UserProfile(models.Model):
        # This field is required.
    user = models.OneToOneField(User)
        # These fields are optional
    developer_name = models.CharField(max_length=100)
    developer_logo = models.FileField()
    developer_headquarters = models.CharField(max_length=100)
    developer_tags = models.CharField(max_length=100)

    def __unicode__(self):
		return self.user.username

from django.forms import ModelForm

class UserForm(forms.ModelForm):
        class Meta:
                model = User
                fields = ['username', 'email', 'password']

class UserProfileForm(forms.ModelForm):
        class Meta:
                model = UserProfile
                fields = ['developer_name', 'developer_logo', 'developer_headquarters', 'developer_tags']

User/forms.py
from django.contrib.auth.models import User
from django import forms
from models import UserProfile

class UserForm(forms.ModelForm):

	password = forms.CharField(widget = forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

class UserProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile 
		fields = ['developer_name', 'developer_logo', 'developer_headquarters', 'developer_tags']

User/views.py
from django.views import generic
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from models import Developer, UserProfile
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login
from django.views.generic import View
from forms import UserForm, UserProfileForm
from django.template import RequestContext
from Code_Fun_Do.settings import MEDIA_ROOT
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView
from django.utils.http import is_safe_url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.core.exceptions import *

class IndexView(generic.ListView):
	template_name = 'User/index.html'

	def get_queryset(self):
		return Developer.objects.all()

class DeveloperDetailsView(generic.ListView):
	template_name = 'User/developerpage.html'

	def get_queryset(self):
		return Developer.objects.all()


class DetailView(generic.DetailView):
	model = Developer
	template_name = 'User/detail.html'

class LoginDetailView(generic.DetailView):
	model = Developer
	template_name = 'User/detaillogin.html'

	#def get_queryset(self):
	#	my_list = Developer.developer_tags.split(",")
	#	return my_list

class UserFormView(View):

	form_class = UserForm
	template_name = 'User/registration_form.html'

	def get(self, request):

		form = self.form_class(None)
		return render(request, self.template_name, {'form':form})

	def post(self, request):

		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			#output clean data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
 			user.set_password(password)

 			user.save()

 			user = authenticate(username=username, password=password)

 			if user is not None:
 				if user.is_active:

 					login(request, user)

 					return redirect('User:developer-add')

 		return render(request, self.template_name, {'form':form})


class DeveloperCreate(CreateView):

	model = Developer
	fields = ['developer_name', 'developer_logo', 'developer_headquarters', 'developer_tags', 'developer_address', 'developer_contact']

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(DeveloperCreate, self).dispatch(*args, **kwargs)

	def form_valid(self, form):

		form.instance.user = self.request.user
		return super(DeveloperCreate, self).form_valid(form)

class DeveloperUpdate(UpdateView):

	model = Developer
	fields = ['developer_name', 'developer_logo', 'developer_headquarters', 'developer_tags','developer_address', 'developer_contact']

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(DeveloperUpdate, self).dispatch(*args, **kwargs)



class DeveloperDelete(DeleteView):

	model = Developer

	success_url = reverse_lazy('User:index')

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(DeveloperDelete, self).dispatch(*args, **kwargs)

class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    template_name ='User/login.html'
    success_url = '/user/'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to

@login_required
def user_logout(request):
    context = RequestContext(request)
    logout(request)
    # Redirect back to index page.
    return HttpResponseRedirect('/user/')


def search(request):

	developers = []

	if request.GET.get('search'):

		search = request.GET.get('search')
		developers = Developer.objects.filter(developer_tags__contains=search)



	return render(request, 'User/search.html', {'developers':developers,})

User/templates/User/base.html
<!DOCTYPE html>
<html>
  <head>

   {% load staticfiles %}
    <meta charset="utf-8">
    <title>Skill Portal</title>
    <link rel="stylesheet" href="../../static/User/css/base.css">
    <link rel="stylesheet" href="../../static/User/css/button.css">
    <script src="../../static/User/js/jquery.min.js" charset="utf-8"></script>
  </head>
  <body>
    <div class='contain'>
      <section class='home active'>
        {% if user.is_authenticated %}
        <h1 class='title'>Welcome to the Digital Age<br> Click on the top left corner.</h1>


        {% else %}
        <h1 class='title'>Welcome to the Digital Age<br> Please Register or Login via <br> the top left corner to continue</h1>


        {% endif %}
      </section>
      <section class='about'>
        <h1 class='title' style="color: blue">About</h1>
        <div style="height:100%; width:100%; display: flex; align-items:center; justify-content: center;">
          <p style="text-align: justify; font-family: 'Raleway', sans-serif; font-size: 25px; line-height: 35px; max-width: 600px; margin-top: -100px; color: blue">

            This webapp is made for those who have a brilliant idea in their minds but lack the resources to turn them into a reality.
            The users can search the databse for "Developers", organisations as well as individuals willing to play their role in the development of
            the nation. The users can straightaway get the contact details of the developers and can contact them on their own, presenting their ideas.
            The webapp also provides an oppurtunity for developers to register and enter their 'Tags': i.e. their specializations. This webapp is under development
            as of now and the next step involves the developers to keep a track on which resources are being demanded the most by users. Knowing the same,
            they can contact the users by their own and collaborate with them for the betterment of the nation.

        </div>
      </section>
      <section class='work'>
        {% if user.is_authenticated %}
         <a href="{% url 'User:developer-detail' %}" style="text-decoration:none;"><h1 class='title'>Go to the developers' page</h1></a>
        {% else %}
         <a href="{% url 'User:register' %}" style="text-decoration:none;"><h1 class='title'>Register as a New Developer or Sign In</h1></a>
         {% endif %}
      </section>
    </div>
    <a class='toggle' href='#'>
      <span class='bar'></span>
      <span class='bar'></span>
      <span class='bar'></span>
    </a>

  </body>
  <script src="../../static/User/js/nav.js" charset="utf-8"></script>
</html>

User/templates/User/base2.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Team DVM</title>
    <link rel="stylesheet" href="../../static/User/css/base.css">
  </head>
  <body>
    <header>
      <div class="logo">
        Team DVM
      </div>
      <nav>
        <ul>
          <li>About</li>
          <li>Usage</li>
        </ul>
      </nav>
    </header>
    <section>
<br><br><br><br><br>Hello
    </section>
    <footer>
      <span>&copy;2017 Team DVM</span>
    </footer>

  </body>
</html>

User/templates/User/base3.html
<!DOCTYPE html>
<html style="height: 100vh !important;">
<head>
	<title>
	{% block title %}
		Registration
	{% endblock %}
	</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="{% static 'Games/style.css' %}" />

	<link href="https://fonts.googleapis.com/css?family=Aref+Ruqaa" rel="stylesheet"type="text/css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<style media="screen">
		input[type="file"] {
			width: 154px;
		}
	</style>
</head>
<body style="background-color:#4CAF50; background-image: none; font-family: 'Raleway', sans-serif !important; height: 100vh;">
	<nav class="navbar" style="padding: 15px 30px; margin-bottom: 0; background: #007f00; border-radius: none;">
		<div class="container-fluid">
			<!-- title -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'User:index' %}">
					<span style="color: #fff; font-size: 20px;">Home</span>
				</a>
			</div>

			<!-- Items -->

			<div class="collapse navbar-collapse" id="topNavBar">

			{% if user.is_authenticated %}

				<ul class="nav navbar-nav">
					<li>
						<a style="background: transparent !important;">
							<span style="color: #fff; font-size: 20px;">Most viewed Tags</span>
						</a>
					</li>
					<form class="navbar-form navbar-left" role="search" method="get" action="/user/search">
					<div class="form-group">
					<input type="text" class="form-control" name="search" value="" placeholder="Search for tags" style="background: transparent; border: 2px solid white; width: 300px; color: white">
					</div>
					<button type="submit" class="btn btn-default" style="color: #4CAF50">Search</button>
					</form>

				</ul>

			{% else %}

				<ul class="nav navbar-nav">
					<li>
						<a href="{% url 'User:developer-detail' %}" style="background: transparent !important;">
							<span style="color: #fff; font-size: 20px;" id="aboutdevs">About the Developers</span>
						</a>
					</li>
					<li class="">
						<a style="background: transparent !important;">
							<span style="color: rgba(200,200,200,0.9); font-size: 20px;">Users</span>
						</a>
					</li>

				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="/user/search">
					<div class="form-group">
					<input type="text" class="form-control" name="search" value="" placeholder="Search for tags" style="background: transparent; border: 2px solid white; width: 300px; color: white">
					</div>
					<button type="submit" class="btn btn-default" style="color: #4CAF50">Search</button>
				</form>

			{% endif %}

				<ul class="nav navbar-nav navbar-right">


					{% if user.is_authenticated %}

					<li class="">
						<a href="{% url 'User:developer-detail' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;" id="aboutdevs">About the Developers</span>
						</a>
					</li>
					<li class="">
						<a href="{% url 'User:logout' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;">Logout</span>
						</a>
					</li>

					{% else %}
					<li class="">
						<a href="{% url 'User:register' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;" id="register">Register</span>
						</a>
					</li>
					<li class="">
						<a href="{% url 'User:login' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;" id="login">Log In</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</div>
		</div>
	</nav>
<div style="height: calc(100% - 100px)">
{% block body %}
{% endblock %}
</div>
</body>
</html>

User/templates/User/detail.html
{% extends 'User/base3.html' %}
{% block title %}
	{{developer.developer_name}}'s Details
{% endblock %}

{% block body %}
<div style="display: flex; height: 100%; align-items: center; justify-content: center;">
<div style="display: flex; align-items: center">
<div style="width:400px; background: #fff; padding: 25px 0; float: left; border-radius: 10px;">
	<center>
		<div style="background: url({{ developer.developer_logo.url }}) center no-repeat; background-size: cover; width: 350px; height: 350px;"></div>
	</center>
		<h1 class="text-center" style="line-height: auto">{{developer.developer_name}}</h1>
		<h3 class="text-center">Headquarters : {{developer.developer_headquarters}}</h3>
		<h4 class="text-center">Address : {{developer.developer_address}}</h4>
		<h5 class="text-center">Contact : {{developer.developer_contact}}</h5>
</div>
<div style="width:400px; background: #fff; padding: 25px 0; float: left; margin-left: 20px; border-radius: 10px">
	<center>
	<div style="width: 150px;">
		<h4>Specialization : </h4>
		<ol>
		{% for tag in developer.developer_tag_list %}
				<li style="color:black!important;">{{tag}}</li>
		{% endfor %}
		</ol>
	</div>
	</center>
</div>
</div>
</div>
{% endblock %}

User/templates/User/detaillogin.html
<!DOCTYPE html>
<html style="height: 100vh !important;">
<head>
	<title>
	{% block title %}
		Registration
	{% endblock %}
	</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="{% static 'Games/style.css' %}" />

	<link href="https://fonts.googleapis.com/css?family=Aref+Ruqaa" rel="stylesheet"type="text/css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<style media="screen">
		input[type="file"] {
			width: 154px;
		}
	</style>
</head>
<body style="background-color:#4CAF50; background-image: none; font-family: 'Raleway', sans-serif !important; height: 100vh;">
	<nav class="navbar" style="padding: 15px 30px; margin-bottom: 0;">
		<div class="container-fluid">
			<!-- title -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'User:index' %}">
					<span style="color: #fff; font-size: 20px;">Home</span>
				</a>
			</div>

			<!-- Items -->
			<div class="collapse navbar-collapse" id="topNavBar">
				<ul class="nav navbar-nav">
					<li>
						<a href="{% url 'User:developer-detail' %}" style="background: transparent !important;">
							<span style="color: #fff; font-size: 20px;">Developers</span>
						</a>
					</li>
					<li class="">
						<a style="background: transparent !important;">
							<span style="color: rgba(200,200,200,0.9); font-size: 20px;">Users</span>
						</a>
					</li>
				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="">
					<div class="form-group">
					<input type="text" class="form-control" name="q" value="" style="background: transparent; border: 2px solid white">
					</div>
					<button type="submit" class="btn btn-default" style="color: #4CAF50">Search</button>
				</form>

				<ul class="nav navbar-nav navbar-right">


					{% if user.is_authenticated %}

					<li class="">
						<a href="{% url 'User:developer-detail' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;">About Me</span>
						</a>
					</li>
					<li class="">
						<a href="{% url 'User:logout' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;">Logout</span>
						</a>
					</li>

					{% else %}
					<li class="">
						<a href="{% url 'User:register' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;">Register</span>
						</a>
					</li>
					<li class="">
						<a href="{% url 'User:login' %}" style="background: transparent">
							<span style="color: #fff; font-size: 20px;">Log In</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</div>
		</div>
	</nav>
<div style="height: calc(100% - 100px)">
	<div style="display: flex; height: 100%; align-items: center; justify-content: center;">
	<div style="display: flex; align-items: center">
	<div style="width:400px; background: #fff; padding: 25px 0; float: left; border-radius: 10px;">
		<center>
			<div style="background: url({{ developer.developer_logo.url }}) center no-repeat; background-size: cover; width: 350px; height: 350px;"></div>
		</center>
			<h1 class="text-center" style="line-height: auto">{{developer.developer_name}}</h1>
			<h3 class="text-center">Headquarters : {{developer.developer_headquarters}}</h3>
			<h4 class="text-center">Address : {{developer.developer_address}}</h4>
			<h5 class="text-center">Contact : {{developer.developer_contact}}</h5>
	</div>
	<div style="width:400px; background: #fff; padding: 25px 0; float: left; margin-left: 20px; border-radius: 10px">
		<center>
		<div style="width: 150px;">
			<h4>Specialization : </h4>
			<ol>
			{% for tag in developer.developer_tag_list %}
					<li style="color:black!important;">{{tag}}</li>
			{% endfor %}
			</ol>
		</div>
		</center>
	</div>
	</div>
	</div>
</div>
</body>
</html>

User/templates/User/developer_form.html
{% extends 'User/base3.html' %}
{% block title %}Add a New Developer{% endblock %}
{% block developers_active %}active{% endblock %}

{% block body %}
<div style="width:100%; height: 100%; display: flex; justify-content: center; align-items: center">
<div style="background:#fff;margin:0;padding:0;display:flex;align-items:center;justify-content:center;width:500px;height:auto;padding-left:50px;padding-right:50px;border-radius:10px">
<div>
<h3 style="margin-top:40px; margin-bottom:60px;">Register as a New Developer!</h3>
				{% if error_message %}
				<p><strong>{{ error_message}} </strong></p>
				{% endif %}
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'User/form-template.html' %}
						<div class="form-group" style="margin-top:20px; margin-bottom: 40px;">
					    <button type="submit" class="btn btn-success">Submit</button>
					  </div>
					</form>
				</div>
        </div>
        </div>
{% endblock %}

User/templates/User/developerpage.html
{% extends 'User/base3.html' %}
{% block body %}
  <style>
    #aboutdevs {
      border-bottom: 2px solid white;
    }
    #developercontainer {
      display: flex;
      justify-content: center;
    }
    ul#developers {

      width: 1280px;
      height: auto;
      padding-left: 0 !important;
      margin-bottom: 0 !important;
    }
    @media all and (max-width: 1279px) {
      ul#developers {
        width: 960px;
      }
    }
    @media all and (max-width: 959px) {
      ul#developers {
        width: 640px;
      }
    }
    @media all and (max-width: 639px) {
      ul#developers {
        width: 320px;
      }
    }
    ul#developers li {
      display: block;
      width: 300px;
      height: auto;
      background: #fff;
      float: left;
      margin: 10px;
      padding: 10px;
      padding-bottom: 20px;
      border-radius: 10px;
    }
    div.profile {
      display: block;
      width: 280px;
      height: 280px;
      background-color: #ddd;
      background-position: center;
      background-size: cover;
    }
    ul#developers li label{
      display: block;
      padding-top: 5px;
      padding-bottom: 0px;
    }
    ul#developers li label:first-of-type {
      padding-top: 20px;
    }
    label[for="name"] {
      font-size: 1.5em;
    }
  </style>
  <div id="developercontainer">

  <font color="black">

  <ul id="developers">
    {% for developer in object_list %}
    <li style="color:black!important;">
      <div class="profile" style="background-image:url({{ developer.developer_logo.url }})"></div>
      <label for="name">
        <span>{{ developer.developer_name }}</span>
      </label>
      <label for="headquarters">
        <span>Headquarters: {{ developer.developer_headquarters }}</span>
      </label>
      <button type="button" class="btn btn-success" name="viewdetails" onclick="location.replace('{% url "User:detail" developer.id %}')">View Details</button>
    </li>
    {% endfor %}

  </ul>
  </font>
  </div>
{% endblock %}

User/templates/User/form-template.html
{% for field in form %}
	<div class="form-group">
		<div>
			<span class="text-danger small">{{ field.errors}}</span>
		</div>
		<div style="display:flex; justify-content: space-between;">
		<label class="control-label">{{ field.label_tag }}</label>
		{{ field }}
		</div>
	</div>
{% endfor %}

User/templates/User/index.html
{% extends 'User/base.html' %}

{% block body %}

	
{% endblock %}

{% block register %}


{% endblock %}

User/templates/User/login.html
{% extends 'User/base3.html' %}
{% block title %}
Login
{% endblock %}
{% block body %}
<style>#login{border-bottom: 2px solid white}</style>
<div style="width:100%; height: 90vh; display: flex; justify-content: center; align-items: center">
<div style="background:#fff;margin:0;padding:0;display:flex;align-items:center;justify-content:center;width:500px;height:auto;padding-left:50px;padding-right:50px;">
<div>
  <h3 style="margin-top:40px; margin-bottom:60px;">Log in to your account</h3>
        <form class="form-horizontal" action="/user/login/" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
        		<div style="display:flex; justify-content: space-between;">
        		<label class="control-label">Username: </label>
          		<input type="text" name="username" value="">
        		</div>
        	</div>
          <div class="form-group">
        		<div style="display:flex; justify-content: space-between;">
              <label class="control-label">Password: </label>
            	<input type="password" name="password" value="">
          	</div>
          </div>
          <div class="form-group" style="margin-top:20px; margin-bottom: 40px;">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

User/templates/User/registration_form.html
{% extends 'User/base3.html' %}
{% block title %}Register{% endblock %}
{% block developers_active %}active{% endblock %}


{% block body %}
<style>#register{border-bottom: 2px solid white}</style>
        <div style="width:100%; height: 90vh; display: flex; justify-content: center; align-items: center">
        <div style="background:#fff;margin:0;padding:0;display:flex;align-items:center;justify-content:center;width:500px;height:auto;padding-left:50px;padding-right:50px;border-radius:10px">
        <div>
{% if registered %}
        <A href="{% url 'User:index' %}">We</A> say: thank you for registering.
{% else %}
				<h3 style="margin-top:40px; margin-bottom:60px;">Register as a New Developer!</h3>
				{% if error_message %}
				<p><strong>{{ error_message}} </strong></p>
				{% endif %}
				  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					  {% csrf_token %}
					  {% include 'User/form-template.html' %}
					  <div class="form-group" style="margin-top:20px; margin-bottom: 40px;">
					    <button type="submit" class="btn btn-success">Submit</button>
					  </div>
          </form>
        </div>
        </div>
        </div>

{% endif %}
{% endblock %}